# Generated by Django 4.1.2 on 2022-10-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fname',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='lname',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
