# Generated by Django 4.1.2 on 2022-10-30 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentInfo',
            fields=[
                ('dpt_id', models.AutoField(primary_key=True, serialize=False)),
                ('dpt_name', models.CharField(max_length=50)),
                ('dpt_entry_date', models.DateTimeField(auto_now_add=True)),
                ('dpt_lastmodify_date', models.DateTimeField(auto_now=True)),
                ('dpt_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyInfo',
            fields=[
                ('fct_id', models.AutoField(primary_key=True, serialize=False)),
                ('fct_name', models.CharField(max_length=50)),
                ('fct_entry_date', models.DateTimeField(auto_now_add=True)),
                ('fct_lastmodify_date', models.DateTimeField(auto_now=True)),
                ('fct_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectInfo',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=50)),
                ('sub_unit', models.SmallIntegerField()),
                ('sub_seat', models.SmallIntegerField()),
                ('sub_schedule', models.CharField(max_length=50)),
                ('sub_entry_date', models.DateTimeField(auto_now_add=True)),
                ('sub_lastmodify_date', models.DateTimeField(auto_now=True)),
                ('sub_active', models.BooleanField(default=True)),
                ('sub_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.departmentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollInfo',
            fields=[
                ('nrl_id', models.AutoField(primary_key=True, serialize=False)),
                ('nrl_status', models.CharField(default='On processing', max_length=10)),
                ('nrl_entry_date', models.DateTimeField(auto_now_add=True)),
                ('nrl_lastmodify_date', models.DateTimeField(auto_now=True)),
                ('nrl_active', models.BooleanField(default=True)),
                ('nrl_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nrl_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.subjectinfo')),
            ],
        ),
        migrations.AddField(
            model_name='departmentinfo',
            name='dpt_faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.facultyinfo'),
        ),
    ]
