# Generated by Django 4.1.2 on 2022-10-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollinfo',
            name='nrl_status',
            field=models.CharField(default='On processing', max_length=20),
        ),
    ]
